// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlInBQpljjUtWjyNsJ_URZvj9SsxgHP48',
    appId: '1:472364929124:web:58d83d73827f1ae2668f71',
    messagingSenderId: '472364929124',
    projectId: 'sms-otp-dc235',
    authDomain: 'sms-otp-dc235.firebaseapp.com',
    storageBucket: 'sms-otp-dc235.firebasestorage.app',
    measurementId: 'G-4JWRJ28ZEV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQ9lbDJj6IQu1aT-NA8zHpHYPyEmYX_9k',
    appId: '1:472364929124:android:6aa8f9baaedfeb60668f71',
    messagingSenderId: '472364929124',
    projectId: 'sms-otp-dc235',
    storageBucket: 'sms-otp-dc235.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuUu1bpYur-0xw8Htk-PWDa21k0yWdYg8',
    appId: '1:472364929124:ios:6579cb5585c73ebc668f71',
    messagingSenderId: '472364929124',
    projectId: 'sms-otp-dc235',
    storageBucket: 'sms-otp-dc235.firebasestorage.app',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuUu1bpYur-0xw8Htk-PWDa21k0yWdYg8',
    appId: '1:472364929124:ios:6579cb5585c73ebc668f71',
    messagingSenderId: '472364929124',
    projectId: 'sms-otp-dc235',
    storageBucket: 'sms-otp-dc235.firebasestorage.app',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlInBQpljjUtWjyNsJ_URZvj9SsxgHP48',
    appId: '1:472364929124:web:88b8cebf55ff786d668f71',
    messagingSenderId: '472364929124',
    projectId: 'sms-otp-dc235',
    authDomain: 'sms-otp-dc235.firebaseapp.com',
    storageBucket: 'sms-otp-dc235.firebasestorage.app',
    measurementId: 'G-PZP7YP3PE5',
  );
}
